Ejemplo LinQ/Models/alumnos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ejemplo_LinQ.Models
{
    public class alumnos
    {
        public int Carnet { get; set; }
        public string Nombre { get; set; }
        public string Materia { get; set; }
        public double Promedio { get; set; }
        public DateTime Fecha { get; set; }


        public List<alumnos> Lista()
        {
            var estudiante1 = new alumnos()
            {
                Carnet = 7845,
                Nombre= "Humberto",
                Materia="Matematica",
                Promedio= 7.8,
                Fecha=DateTime.Now

            };
            var estudiante2 = new alumnos()
            {
                Carnet = 9901,
                Nombre = "Roberto",
                Materia = "Fisica I",
                Promedio = 7.6,
                Fecha = DateTime.Now

            };
            var estudiante3 = new alumnos()
            {
                Carnet = 8745,
                Nombre = "Marta",
                Materia = "Quimica",
                Promedio = 8.9,
                Fecha = DateTime.Now

            };
            var estudiante4 = new alumnos()
            {
                Carnet = 1024,
                Nombre = "Maria",
                Materia = "Cálculo",
                Promedio = 6.8,
                Fecha = DateTime.Now

            };
            var estudiante5 = new alumnos()
            {
                Carnet = 1041,
                Nombre = "Marcos",
                Materia = "Fisica II",
                Promedio = 5.8,
                Fecha = DateTime.Now

            };
            return new List<alumnos>() {estudiante1,estudiante2,estudiante3,estudiante4,estudiante5 };
        }
    }

}

Ejemplo LinQ/Controllers/LinQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejemplo_LinQ.Controllers
{
    public class LinQController : Controller
    {
        // GET: LinQ
        public ActionResult Index()
        {
            int[] numero = { 2, 5, -9, -7, 3, 4, 96, -78, -85,55, 43,4, -78, -56, 96,85, 74, -9, 85, -98,85 };

            //Numeros Iguales
            var query1 = from n in numero
                         where n == 85
                         select n;
            ViewBag.dato = query1;

            //Numeros pares
                List<int> numQuery2 =
                (from n in numero
                where (n % 2) == 0
                select n).ToList();

                ViewBag.dato2 = numQuery2;

            //Mayor que
            var query3 =
              from n in numero
              where n > 5 && n < 60
              select n;

            ViewBag.dato3 = query3;

            //ordenar de mayor a menor
            var query4 = from n in numero
                         orderby n descending
                         select n;

            ViewBag.dato4 = query4;
            //ordenar de menor a mayor
            var query5 = from n in numero
                         orderby n
                         select n;

            ViewBag.dato5 = query5;


            return View();
        }

        public ActionResult lista()
        {
            List<string> materias = new List<string>()
            {
                "Matematicas", "algoritmia","Mvc basico","historia de internet", "linq","use tools"
            };
            //Empiezan con la letra x
            var query = from n in materias
                        where n.StartsWith("M")
                        select n;
            ViewBag.dato = query;

            //Terminan con la letra x
            var query2 = from n in materias
                        where n.EndsWith("a")
                        select n;
            ViewBag.dato1 = query2;

            //
            var query3 = from n in materias
                         where n.Contains("a")
                         select n;
            ViewBag.dato2 = query3;





            return View(query2.ToList());
        }

    }
}

Ejemplo LinQ/Controllers/studentController.cs
using Ejemplo_LinQ.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ejemplo_LinQ.Controllers
{
    public class studentController : Controller
    {
        alumnos db = new alumnos();
        // GET: student
        public ActionResult Index()
        {
            var Listado = db.Lista();


            return View(Listado.ToList());
        }
    }
}

Ejemplo LinQ/Views/LinQ/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>

    table {
        width: 100%;
        font-size: 11pt;
    }

    table, th, td {
        border: 2px solid #cecece;
        border-collapse: collapse;
        text-align: center;
        table-layout: fixed;
    }

    .selected {
        background-color: #f36f48;
        font-weight: bold;
        color: white;
    }

    li {
        margin-bottom: 15px;
        font-weight: bold;
    }
</style>
<br />
<br />
<div class="section"/>
<h1>Hola soy la pajarita</h1>
<table>
    <tr>
        <th class="selected">Numeros Iguales</th>
  
        <th class="selected">Numeros Pares</th>
    
        <th class="selected">Numeros Mayor que</th>
   
        <th class="selected">Numeros de mayor a menor</th>

        <th class="selected">Numeros de menor a mayor</th>
    </tr>


    <tr>

        <td>

            @foreach (var item in ViewBag.dato)
            {

                <div>@item</div>

            }

        </td>




        <td>

            @foreach (var item in ViewBag.dato2)
            {

                <div>@item</div>

            }

        </td>





        <td>

            @foreach (var item in ViewBag.dato3)
            {

                <div>@item</div>

            }

        </td>

        <td>

            @foreach (var item in ViewBag.dato4)
            {

                <div>@item</div>

            }

        </td>
        <td>

            @foreach (var item in ViewBag.dato5)
            {

                <div>@item</div>

            }

        </td>
    </tr>
</table>
               

            
        


   
        

Ejemplo LinQ/Views/LinQ/lista.cshtml
@model List<string>


<style>

    table {
        width: 100%;
        font-size: 11pt;
    }

    table, th, td {
        border: 2px solid #cecece;
        border-collapse: collapse;
        text-align: center;
        table-layout: fixed;
    }

    .selected {
        background-color: #f36f48;
        font-weight: bold;
        color: white;
    }

    li {
        margin-bottom: 15px;
        font-weight: bold;
    }
</style>

<br />
<div class="section" />
<table>
    <tr>
        <th class="selected">Letra Inicial</th>
        <th class="selected">Ultima letra</th>
        <th class="selected">Que contenga la letra</th>
        
        
    </tr>
    <tr>

        <td>

            @foreach (var item in ViewBag.dato)
            {

                <div>@item</div>

            }

        </td>


        <td>
            @foreach (var item in ViewBag.dato1)
            {


                <div>@item</div>

            }
        </td>

        <td>
            @foreach (var item in ViewBag.dato2)
            {


                <div>@item</div>

            }
        </td>
    </tr>
    </table>

Ejemplo LinQ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Numeros", "Index", "LinQ", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Lista", "lista", "LinQ", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Alumnos", "Index", "student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Ejemplo LinQ/Views/student/Index.cshtml
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>

    table {
        width: 100%;
        font-size: 11pt;
    }

    table, th, td {
        border: 2px solid #cecece;
        border-collapse: collapse;
        text-align: center;
        table-layout: fixed;
    }

    .selected {
        background-color: #f36f48;
        font-weight: bold;
        color: white;
    }

    li {
        margin-bottom: 15px;
        font-weight: bold;
    }

    input {
        border: none;
        padding-top: 5px;
        width: 95%;
        transform: translateX(-50%);
        margin-left: 50%;
        text-align: center;
        color: rgba(0,0,0,0.8);
        background-color: rgba(0,0,0,0);
    }

    #search {
        width: 120px;
        height: 30px;
        border: 2px solid #E5E5E5;
        background-color: #E5E5E5;
        border-radius: 1em;
        margin-top: 90px;
        margin-left: 50%;
        overflow: hidden;
        transition-duration: .6s;
        transform: translateX(-50%);
    }

        #search input {
            outline: none;
        }

        #search:hover {
            width: 40%;
        }


    .w3-button {
        width: 100px;
        text-align: center;
    }
</style>

<br />
<div>
    <div id="search">
        <input type="text" placeholder='Buscar' data-search />

    </div>
    <br />
    <center><p><button class="w3-button w3-deep-orange">Buscar</button></p></center>
    <hr />
    <div class="section" />
    <table>
        <tr>
            <th class="selected">Carnet</th>
            <th class="selected">Nombre</th>
            <th class="selected">Materia</th>
            <th class="selected">Estado</th>
            <th class="selected">Fecha</th>




        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <th>@item.Carnet</th>
                <th>@item.Nombre</th>
                <th>@item.Materia</th>
                <th>@item.Promedio</th>
                <th>@item.Fecha</th>


            </tr>



        }

    </table>
</div>